### PR TITLE
Created new AutonomyLogic class to handle autonomy logic

### PR DESCRIPTION
**Pull request by JWhitney406**
Sam and I created a new class to handle all the Autonomy Logic.

Please review:
@angustomlinson @Mammothskier

### CODE REVIEW

**Comment by angustomlinson** [comment]
+1 Code changes look good. Does this code run?

**Comment by JWhitney406** [comment]
Yes, tested on my Tango. No notable differences from the previous version of the app.

**Comment by Mammothskier** [comment]
Code looks good. Did any logic change?

**Comment by JWhitney406** [comment]
Not really, the only thing was the removal of a update IR method which was obsolete.

**Pull request merged**
